sudo: false
language: haskell # for shellcheck
cache:
  directories:
  - $HOME/.cabal/packages
install:
- cabal install shellcheck
script:
# Ignore SC1091: Not following
- shellcheck caribe -e SC1091
